# Generated by Django 5.0.3 on 2024-03-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150)),
                ('data', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/images')),
                ('is_liked', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
